name: Build cross-compilation images

on:
  push:
    branches:
      - "master"
    paths:
      - "docker/*"

jobs:
  docker:
    strategy:
      matrix:
        arch:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-gnu
          - aarch64-apple-darwin
          - x86_64-apple-darwin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        env:
          RELEASE: true
        run: make ${{ matrix.arch }}
